from PyQt5 import QtWidgets
from PyQt5 import QtCore
from PyQt5.QtGui import *
from PyQt5.QtGui import QIcon,QPixmap
import sys
from bs4 import BeautifulSoup
import requests
import css_code
import os
from os import path


def Wavelength():
    def exit3():
        l1.show()
        b1.show()
        b2.show()
        b3.show()
        l5.hide()
        e2.hide()
        l6.hide()
        l7.hide()
        b7.hide()
        b6.hide()
        l9.hide()
    def math2():
        n4=QIntValidator()
        n5=e2.text()
        e2.setValidator(n4)
        if int(n5)>=100 or n5>=280:
            l9.setText('بعيده')
        elif int(n5)>=280 or n5>=315:
            l9.setText('متوسطه')
        elif int(n5)>=315 or n5>=400:
            l9.setText('قريبه')
        else:
            m3=QtWidgets.QMessageBox.warning(program, 'Cps', 'هناك خطأ في العمليه الحسابيه')
    l1.hide()
    b1.hide()
    b2.hide()
    b3.hide()
    l5=QtWidgets.QLabel(program)
    i4=QPixmap('icons//ozone-layer-1.png').scaled(200,200)
    l5.setPixmap(i4)
    l5.resize(200,200)
    l5.move(600,10)
    l5.show()
    e2=QtWidgets.QLineEdit(program)
    e2.show()
    e2.setStyleSheet(css_code.css6)
    e2.resize(200,40)
    e2.setPlaceholderText('الطول الموجي')
    e2.move(800, 400)
    l6=QtWidgets.QLabel(program)
    i5=QPixmap('icons//arrow.png').scaled(200,200)
    l6.setPixmap(i5)
    l6.resize(200,200)
    l6.move(550,320)
    l6.show()
    l7=QtWidgets.QLabel('النوع :',program)
    l7.move(400, 400)
    l7.setStyleSheet(css_code.css5)
    l7.resize(100,40)
    l7.show()
    l8=QtWidgets.QLabel(program)
    l8.move(350, 400)
    l8.setStyleSheet(css_code.css5)
    l8.resize(100,40)
    l8.show()
    l9=QtWidgets.QLabel(program)
    l9.move(300, 400)
    l9.setStyleSheet(css_code.css5)
    l9.resize(100,40)
    l9.show()
    b7=QtWidgets.QPushButton('حساب',program)
    b7.setStyleSheet(css_code.css3)
    b7.resize(200, 50)
    b7.move(550, 520)
    b7.setIcon(QIcon('icons//math.png'))
    b7.setIconSize(QtCore.QSize(50, 40))
    b7.show()
    b7.clicked.connect(math2)
    b6=QtWidgets.QPushButton('رجوع',program)
    b6.setStyleSheet(css_code.css8)
    b6.resize(200, 50)
    b6.move(550, 620)
    b6.setIcon(QIcon('icons//back.png'))
    b6.setIconSize(QtCore.QSize(50, 40))
    b6.clicked.connect(exit3)
    b6.show()
def exit1():
    m2=QtWidgets.QMessageBox.question(program, 'Cps', 'هل تريد الخروج؟')
    if m2==QtWidgets.QMessageBox.Yes:
        exit()
def Ozone():
    def exit2():
        l1.show()
        b1.show()
        b2.show()
        b3.show()
        l2.hide()
        e1.hide()
        l3.hide()
        l4.hide()
        b5.hide()
        b6.hide()
        l10.hide()
    def math():
        n1=QIntValidator()
        n2=e1.text()
        e1.setValidator(n1)
        if 300<=int(n2):
            m2=QtWidgets.QMessageBox.warning(program, 'Cps', 'هناك خطأ في العمليه الحسابيه')
        else:
            n3=300-int(n2)
            l4.setText(str(n3))
    l1.hide()
    b1.hide()
    b2.hide()
    b3.hide()
    l2=QtWidgets.QLabel(program)
    i2=QPixmap('icons//earth.png').scaled(200,200)
    l2.setPixmap(i2)
    l2.resize(200,200)
    l2.move(600,10)
    l2.show()
    e1=QtWidgets.QLineEdit(program)
    e1.show()
    e1.setStyleSheet(css_code.css6)
    e1.resize(200,40)
    e1.setPlaceholderText("درجه الاوزون")
    e1.move(800, 400)
    l3=QtWidgets.QLabel(program)
    i3=QPixmap('icons//arrow.png').scaled(200,200)
    l3.setPixmap(i3)
    l3.resize(200,200)
    l3.move(550,320)
    l3.show()
    l4=QtWidgets.QLabel(program)
    l4.setStyleSheet(css_code.css5)
    l4.move(300, 408)
    l4.show()
    l10=QtWidgets.QLabel('نسبه التأكل :',program)
    l10.setStyleSheet(css_code.css5)
    l10.resize(170, 40)
    l10.move(350, 400)
    l10.show()
    b5=QtWidgets.QPushButton('حساب',program)
    b5.setStyleSheet(css_code.css4)
    b5.resize(200, 50)
    b5.move(550, 550)
    b5.setIcon(QIcon('icons//math.png'))
    b5.setIconSize(QtCore.QSize(50, 40))
    b5.show()
    b5.clicked.connect(math)
    b6=QtWidgets.QPushButton('رجوع',program)
    b6.setStyleSheet(css_code.css8)
    b6.resize(200, 50)
    b6.move(550, 620)
    b6.setIcon(QIcon('icons//back.png'))
    b6.setIconSize(QtCore.QSize(50, 40))
    b6.show()
    b6.clicked.connect(exit2)
def weather():
    def exit3():
        l2.hide()
        l3.hide()
        l4.hide()
        l5.hide()
        l6.hide()
        b6.hide()
        l1.show()
        b1.show()
        b2.show()
        b3.show()
    weater1=[]
    wind=[]
    weater3=[]
    weater4=[]
    l1.hide()
    b1.hide()
    b2.hide()
    b3.hide()
    l2=QtWidgets.QLabel(program)
    l2.setStyleSheet(css_code.css2)
    l2.move(300,80)
    l2.resize(200, 50)
    l3=QtWidgets.QLabel('درجه الحراره في دمنهور',program)
    l3.setStyleSheet(css_code.css2)
    l3.move(500, 40)
    l3.resize(500, 100)
    l3.show()
    l4=QtWidgets.QLabel('سرعه الرياح',program)
    l4.setStyleSheet(css_code.css2)
    l4.move(650, 200)
    l4.resize(500, 100)
    l4.show()
    l5=QtWidgets.QLabel(program)
    l5.setStyleSheet(css_code.css2)
    l5.move(640, 200)
    l5.resize(200, 100)
    l5.show()
    l6=QtWidgets.QLabel(program)
    i3=QPixmap('icons//wind.png').scaled(100,100)
    l6.setPixmap(i3)
    l6.resize(200,200)
    l6.move(1200,160)
    l6.show()
    b6=QtWidgets.QPushButton('رجوع',program)
    b6.setStyleSheet(css_code.css8)
    b6.resize(200, 50)
    b6.move(550, 620)
    b6.setIcon(QIcon('icons//back.png'))
    b6.setIconSize(QtCore.QSize(50, 40))
    b6.show()
    b6.clicked.connect(exit3)
    try:
        r1=requests.get('https://www.msn.com/en-us/weather/forecast/in-Qesm-Damanhour,Al-Buhayrah?ocid=ansmsnweather&loc=eyJsIjoiUWVzbSBEYW1hbmhvdXIiLCJyIjoiQWwgQnVoYXlyYWgiLCJyMiI6IkRhbWFuaG91ciIsImMiOiJFZ3lwdCIsImkiOiJFRyIsImciOiJlbi11cyIsIngiOiIzMC40NjQiLCJ5IjoiMzEuMDMzIn0%3D&weadegreetype=C')
        r2=r1.content
        x1=BeautifulSoup(r2,'lxml')
        x2=x1.find_all('a',{"class":"summaryTemperatureCompact-E1_1 summaryTemperatureHover-E1_1"})
        for i in range(len(x2)):
            weater1.append(x2[i].text)
        l2.setText(weater1[0])
        l2.show()
        x3=x1.find_all('div',{"id":"CurrentDetailLineWindValue"})
        for i2 in range(len(x2)):
            wind.append(x3[i2].text)
        l5.setText(wind[0])
    except:
        l2.hide()
        l3.hide()
        l4.hide()
        l5.hide()
        l6.hide()
        b4.hide()
        m1=QtWidgets.QMessageBox.warning(program, 'Cps', 'حدث خطأ')
        exit()
#pushButton.setIconSize(QtCore.QSize(100, 100))
app=QtWidgets.QApplication(sys.argv)
program=QtWidgets.QMainWindow()
program.setWindowTitle('Cps')
program.setStyleSheet(css_code.css1)
l1=QtWidgets.QLabel(program)
i1=QPixmap('icons//Cps.png')
l1.setPixmap(i1)
l1.resize(400,300)
l1.move(500,10)
b1=QtWidgets.QPushButton('الطقس', program)
b1.setIcon(QIcon('icons//sun.png'))
b1.setIconSize(QtCore.QSize(50, 40))
b1.clicked.connect(weather)
b1.setStyleSheet(css_code.css4)
b1.resize(250, 50)
b1.move(10, 400)
b2=QtWidgets.QPushButton('الاوزون', program)
b2.clicked.connect(Ozone)
b2.setStyleSheet(css_code.css4)
b2.resize(200, 50)
b2.move(350, 400)
b2.setIcon(QIcon('icons//earth-1.png'))
b2.setIconSize(QtCore.QSize(50, 40))
b3=QtWidgets.QPushButton('الطول الموجي', program)
b3.clicked.connect(Wavelength)
b3.setStyleSheet(css_code.css4)
b3.resize(250, 50)
b3.move(650, 400)
b3.setIcon(QIcon('icons//ozone-layer.png'))
b3.setIconSize(QtCore.QSize(50, 40))
b4=QtWidgets.QPushButton('خروج',program)
b4.setStyleSheet(css_code.css7)
b4.resize(150, 50)
b4.move(1220, 660)
b4.setIcon(QIcon('icons//exit.png'))
b4.setIconSize(QtCore.QSize(50, 40))
b4.show()
b4.clicked.connect(exit1)
program.showMaximized()
app.exec_()